services:
  - type: web
    name: foodordering-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: MAILER_SMTP_HOST
        value: smtp-relay.brevo.com
      - key: MAILER_SMTP_PORT
        value: 587
      - key: MAILER_SMTP_USE_TLS
        value: True
      - key: MAILER_SMTP_USE_SSL
        value: False
      - key: MAILER_SMTP_USER
        value: a91efd001@smtp-brevo.com
      - key: MAILER_SMTP_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: OrderBites <ralphyvillarojo0203@gmail.com>
