from django.urls import path
from . import views

urlpatterns = [
    path('', views.store_list, name='store_list'),
    path('categories/', views.get_categories, name='get_categories'),
    path('locations/search/', views.location_search, name='location_search'),
    path('locations/zone-check/', views.check_delivery_zone, name='check_delivery_zone'),
    path('locations/saved/', views.saved_locations, name='saved_locations'),
    path('address-book/', views.address_book, name='address_book'),
    path('address-book/<int:pk>/', views.address_book_detail, name='address_book_detail'),
    path('suki/balance/', views.suki_balance, name='suki_balance'),
    path('admin/restaurants/', views.manage_restaurants, name='manage_restaurants'),
    path('admin/store-admins/', views.list_store_admins, name='list_store_admins'),
    path('manage/<int:restaurant_id>/', views.manage_restaurant_settings, name='manage_restaurant_settings'),
    path('<int:store_id>/', views.store_detail, name='store_detail'),
    path('<int:store_id>/menu/', views.store_menu, name='store_menu'),
    path('menu/add/', views.add_menu_item, name='add_menu_item'),
    path('menu/categories/', views.manage_menu_categories, name='manage_menu_categories'),
    path('menu/categories/<int:category_id>/', views.delete_menu_category, name='delete_menu_category'),
    path('menu/<int:item_id>/', views.manage_menu_item, name='manage_menu_item'),
    path('orders/create/', views.create_order, name='create_order'),
    path('orders/my/', views.my_orders, name='my_orders'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/store/<int:store_id>/', views.store_orders, name='store_orders'),
    path('orders/<int:order_id>/status/', views.update_order_status, name='update_order_status'),
    path('orders/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('delivery/orders/', views.delivery_orders, name='delivery_orders'),
    path('delivery/<int:order_id>/accept/', views.accept_delivery, name='accept_delivery'),
    path('delivery/<int:order_id>/location/', views.update_rider_location, name='update_rider_location'),
    path('delivery/<int:order_id>/complete/', views.complete_delivery, name='complete_delivery'),
    path('orders/<int:order_id>/messages/', views.order_messages, name='order_messages'),
    path('orders/<int:order_id>/rate/', views.submit_rating, name='submit_rating'),
    path('riders/<int:rider_id>/rating/', views.rider_rating, name='rider_rating'),
    path('restaurants/<int:restaurant_id>/rating/', views.restaurant_rating, name='restaurant_rating'),
    path('payments/gcash/create/', views.create_gcash_payment, name='create_gcash_payment'),
    path('payments/gcash/check/<str:link_id>/', views.check_gcash_payment, name='check_gcash_payment'),
]
