# Generated by Django 6.0.1 on 2026-03-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_locked_until_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('store_admin', 'Store Admin'), ('delivery', 'Delivery Rider')], default='customer', max_length=20),
        ),
    ]
