# Generated by Django 6.0.1 on 2026-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='motorcycle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
