# Generated by Django 6.0.3 on 2026-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_driver_license_user_motorcycle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='motorcycle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_docs/'),
        ),
    ]
