# Generated by Django 6.0.3 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_front',
            field=models.ImageField(blank=True, null=True, upload_to='rider_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_left',
            field=models.ImageField(blank=True, null=True, upload_to='rider_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_right',
            field=models.ImageField(blank=True, null=True, upload_to='rider_docs/'),
        ),
    ]
