# Generated by Django 6.0.4 on 2026-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_latitude_alter_user_longitude'),
        ('accounts', '0011_fix_coordinate_decimal_fields'),
    ]

    operations = [
    ]
