# Generated by Django 6.0.1 on 2026-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('chicken', 'Chicken'), ('pizza', 'Pizza'), ('drinks', 'Drinks'), ('fries', 'Fries'), ('sandwich', 'Sandwich'), ('dessert', 'Dessert'), ('coffee', 'Coffee'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
