# Generated by Django 6.0.1 on 2026-02-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(default=100),
        ),
    ]
