# Generated by Django 6.0.1 on 2026-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_menuitem_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash'), ('CARD', 'Credit/Debit Card')], default='COD', max_length=10),
        ),
    ]
