# Generated by Django 6.0.1 on 2026-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_restaurant_admin_alter_restaurant_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='RestaurantCategory',
        ),
    ]
