# Generated by Django 6.0.3 on 2026-03-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_delete_category_delete_restaurantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
