# Generated by Django 6.0.3 on 2026-04-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_menucategory_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='emoji',
        ),
    ]
