# Generated by Django 6.0.3 on 2026-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_remove_restaurant_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
    ]
