# Generated by Django 6.0.3 on 2026-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_order_delivery_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
