# Generated by Django 6.0.3 on 2026-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_restaurant_closing_time_restaurant_is_24hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
