# Generated by Django 6.0.4 on 2026-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_sukiconfig_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sukiconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
